name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # MongoDB Configuration
      MONGODB_URI: mongodb://localhost:27017/test
      MONGODB_DB_NAME: test
      
      # Redis Configuration
      REDIS_URL: redis://localhost:6379
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      
      # Application Configuration
      NODE_ENV: test
      CORS_ORIGIN: http://localhost:3000
      PORT: 4000

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install and Test Backend
      working-directory: ./backend
      run: |
        npm install
        npm test
    
    - name: Upload backend test coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: backend/coverage/
        retention-days: 5

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install and Build Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build
    
    - name: Upload frontend build
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build/
        retention-days: 5